"""initial schema

Revision ID: a57b82ae0f18
Revises: 
Create Date: 2026-02-10 18:10:58.184277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a57b82ae0f18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atelier_activite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secteur', sa.String(length=80), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_atelier', sa.String(length=30), nullable=False),
    sa.Column('capacite_defaut', sa.Integer(), nullable=True),
    sa.Column('heures_dispo_defaut_mois', sa.Float(), nullable=True),
    sa.Column('duree_defaut_minutes', sa.Integer(), nullable=True),
    sa.Column('motifs_json', sa.Text(), nullable=True),
    sa.Column('modele_docx_collectif', sa.String(length=255), nullable=True),
    sa.Column('modele_docx_individuel', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('atelier_activite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atelier_activite_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_atelier_activite_secteur'), ['secteur'], unique=False)

    op.create_table('instance_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=120), nullable=True),
    sa.Column('organization_name', sa.String(length=180), nullable=True),
    sa.Column('app_logo_path', sa.String(length=255), nullable=True),
    sa.Column('organization_logo_path', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partenaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=180), nullable=False),
    sa.Column('contact_nom', sa.String(length=120), nullable=True),
    sa.Column('contact_prenom', sa.String(length=120), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('email_contact', sa.String(length=180), nullable=True),
    sa.Column('email_general', sa.String(length=180), nullable=True),
    sa.Column('tel_contact', sa.String(length=60), nullable=True),
    sa.Column('tel_general', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_code'), ['code'], unique=True)

    op.create_table('projet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('secteur', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cr_filename', sa.String(length=255), nullable=True),
    sa.Column('cr_original_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quartier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ville', sa.String(length=80), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_qpv', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ville', 'nom', name='uq_quartier_ville_nom')
    )
    op.create_table('questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referentiel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_code'), ['code'], unique=True)

    op.create_table('secteur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('secteur', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secteur_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_secteur_label'), ['label'], unique=True)

    op.create_table('subvention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('secteur', sa.String(length=80), nullable=False),
    sa.Column('annee_exercice', sa.Integer(), nullable=False),
    sa.Column('montant_demande', sa.Float(), nullable=True),
    sa.Column('montant_attribue', sa.Float(), nullable=True),
    sa.Column('montant_recu', sa.Float(), nullable=True),
    sa.Column('est_archive', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('secteur_assigne', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('atelier_capacite_mois',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atelier_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('heures_dispo', sa.Float(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['atelier_id'], ['atelier_activite.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atelier_id', 'annee', 'mois', name='uq_atelier_capacite_mois')
    )
    op.create_table('bilan_lourd_narratif',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('secteur', sa.String(length=80), nullable=False),
    sa.Column('faits_marquants', sa.Text(), nullable=True),
    sa.Column('difficultes', sa.Text(), nullable=True),
    sa.Column('perspectives', sa.Text(), nullable=True),
    sa.Column('photos_json', sa.Text(), nullable=True),
    sa.Column('timeline_json', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annee', 'secteur', name='uq_bilan_lourd_narratif_annee_secteur')
    )
    with op.batch_alter_table('bilan_lourd_narratif', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bilan_lourd_narratif_annee'), ['annee'], unique=False)
        batch_op.create_index(batch_op.f('ix_bilan_lourd_narratif_secteur'), ['secteur'], unique=False)

    op.create_table('charge_projet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('bloc', sa.String(length=20), nullable=False),
    sa.Column('code_plan', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('montant_previsionnel', sa.Float(), nullable=True),
    sa.Column('montant_reel', sa.Float(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projet_id'], ['projet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referentiel_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['referentiel_id'], ['referentiel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facture_achat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secteur_principal', sa.String(length=80), nullable=False),
    sa.Column('fournisseur', sa.String(length=180), nullable=True),
    sa.Column('reference_facture', sa.String(length=120), nullable=True),
    sa.Column('date_facture', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ligne_budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subvention_id', sa.Integer(), nullable=False),
    sa.Column('nature', sa.String(length=10), nullable=False),
    sa.Column('compte', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=200), nullable=False),
    sa.Column('montant_base', sa.Float(), nullable=True),
    sa.Column('montant_reel', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subvention_id'], ['subvention.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partenaire_intervention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partenaire_id', sa.Integer(), nullable=False),
    sa.Column('secteur', sa.String(length=80), nullable=True),
    sa.Column('date_intervention', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['partenaire_id'], ['partenaire.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partenaire_secteur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partenaire_id', sa.Integer(), nullable=False),
    sa.Column('secteur', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['partenaire_id'], ['partenaire.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partenaire_id', 'secteur', name='uq_partenaire_secteur')
    )
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('prenom', sa.String(length=120), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('ville', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('telephone', sa.String(length=60), nullable=True),
    sa.Column('genre', sa.String(length=20), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('type_public', sa.String(length=2), nullable=False),
    sa.Column('quartier_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_secteur', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['quartier_id'], ['quartier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periode_financement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secteur', sa.String(length=80), nullable=True),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('periode_financement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_periode_financement_date_debut'), ['date_debut'], unique=False)
        batch_op.create_index(batch_op.f('ix_periode_financement_date_fin'), ['date_fin'], unique=False)
        batch_op.create_index(batch_op.f('ix_periode_financement_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_periode_financement_secteur'), ['secteur'], unique=False)

    op.create_table('produit_projet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('financeur', sa.String(length=255), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('montant_demande', sa.Float(), nullable=True),
    sa.Column('montant_accorde', sa.Float(), nullable=True),
    sa.Column('montant_recu', sa.Float(), nullable=True),
    sa.Column('reference_dossier', sa.String(length=120), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projet_id'], ['projet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projet_atelier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('atelier_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atelier_id'], ['atelier_activite.id'], ),
    sa.ForeignKeyConstraint(['projet_id'], ['projet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projet_id', 'atelier_id', name='uq_projet_atelier')
    )
    with op.batch_alter_table('projet_atelier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projet_atelier_atelier_id'), ['atelier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projet_atelier_projet_id'), ['projet_id'], unique=False)

    op.create_table('projet_indicateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projet_id'], ['projet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projet_id', 'code', name='uq_projet_indicateur_code')
    )
    with op.batch_alter_table('projet_indicateur', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projet_indicateur_projet_id'), ['projet_id'], unique=False)

    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaire.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionnaire_atelier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_id', sa.Integer(), nullable=False),
    sa.Column('atelier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atelier_id'], ['atelier_activite.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaire.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('questionnaire_id', 'atelier_id', name='uq_questionnaire_atelier')
    )
    op.create_table('questionnaire_secteur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_id', sa.Integer(), nullable=False),
    sa.Column('secteur', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaire.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('questionnaire_id', 'secteur', name='uq_questionnaire_secteur')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('session_activite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atelier_id', sa.Integer(), nullable=False),
    sa.Column('secteur', sa.String(length=80), nullable=False),
    sa.Column('session_type', sa.String(length=30), nullable=False),
    sa.Column('date_session', sa.Date(), nullable=True),
    sa.Column('heure_debut', sa.String(length=10), nullable=True),
    sa.Column('heure_fin', sa.String(length=10), nullable=True),
    sa.Column('capacite', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('rdv_date', sa.Date(), nullable=True),
    sa.Column('rdv_debut', sa.String(length=10), nullable=True),
    sa.Column('rdv_fin', sa.String(length=10), nullable=True),
    sa.Column('duree_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('kiosk_open', sa.Boolean(), nullable=True),
    sa.Column('kiosk_pin', sa.String(length=10), nullable=True),
    sa.Column('kiosk_token', sa.String(length=64), nullable=True),
    sa.Column('kiosk_opened_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atelier_id'], ['atelier_activite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_activite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_activite_date_session'), ['date_session'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_activite_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_activite_kiosk_open'), ['kiosk_open'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_activite_kiosk_pin'), ['kiosk_pin'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_activite_kiosk_token'), ['kiosk_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_activite_rdv_date'), ['rdv_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_activite_secteur'), ['secteur'], unique=False)

    op.create_table('subvention_projet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('subvention_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projet_id'], ['projet.id'], ),
    sa.ForeignKeyConstraint(['subvention_id'], ['subvention.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projet_id', 'subvention_id', name='uq_projet_subvention')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('archive_emargement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secteur', sa.String(length=80), nullable=False),
    sa.Column('atelier_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=True),
    sa.Column('docx_path', sa.String(length=255), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('corrected_docx_path', sa.String(length=255), nullable=True),
    sa.Column('corrected_pdf_path', sa.String(length=255), nullable=True),
    sa.Column('last_emailed_to', sa.String(length=255), nullable=True),
    sa.Column('last_emailed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atelier_id'], ['atelier_activite.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session_activite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archive_emargement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archive_emargement_secteur'), ['secteur'], unique=False)

    op.create_table('atelier_competence',
    sa.Column('atelier_id', sa.Integer(), nullable=False),
    sa.Column('competence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atelier_id'], ['atelier_activite.id'], ),
    sa.ForeignKeyConstraint(['competence_id'], ['competence.id'], ),
    sa.PrimaryKeyConstraint('atelier_id', 'competence_id')
    )
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('competence_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('etat', sa.Integer(), nullable=False),
    sa.Column('date_evaluation', sa.Date(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['competence_id'], ['competence.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session_activite.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'competence_id', 'session_id', name='uq_eval_participant_competence_session')
    )
    op.create_table('facture_ligne',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=False),
    sa.Column('secteur', sa.String(length=80), nullable=False),
    sa.Column('financement_type', sa.String(length=30), nullable=False),
    sa.Column('a_ventiler', sa.Boolean(), nullable=True),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=True),
    sa.Column('montant_ligne', sa.Float(), nullable=True),
    sa.Column('ligne_budget_id', sa.Integer(), nullable=True),
    sa.Column('charge_projet_id', sa.Integer(), nullable=True),
    sa.Column('subvention_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['charge_projet_id'], ['charge_projet.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facture_id'], ['facture_achat.id'], ),
    sa.ForeignKeyConstraint(['ligne_budget_id'], ['ligne_budget.id'], ),
    sa.ForeignKeyConstraint(['subvention_id'], ['subvention.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objectif',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seuil_validation', sa.Float(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=True),
    sa.Column('atelier_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atelier_id'], ['atelier_activite.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['objectif.id'], ),
    sa.ForeignKeyConstraint(['projet_id'], ['projet.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session_activite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presence_activite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('motif', sa.String(length=180), nullable=True),
    sa.Column('motif_autre', sa.String(length=255), nullable=True),
    sa.Column('signature_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session_activite.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'participant_id', name='uq_presence_session_participant')
    )
    op.create_table('projet_competence',
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('competence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competence_id'], ['competence.id'], ),
    sa.ForeignKeyConstraint(['projet_id'], ['projet.id'], ),
    sa.PrimaryKeyConstraint('projet_id', 'competence_id')
    )
    op.create_table('questionnaire_response_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('atelier_id', sa.Integer(), nullable=True),
    sa.Column('secteur', sa.String(length=80), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atelier_id'], ['atelier_activite.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaire.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session_activite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_competence',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('competence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competence_id'], ['competence.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session_activite.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'competence_id')
    )
    op.create_table('ventilation_projet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('montant_ventile', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['charge_id'], ['charge_projet.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produit_id'], ['produit_projet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ligne_budget_id', sa.Integer(), nullable=True),
    sa.Column('charge_projet_id', sa.Integer(), nullable=True),
    sa.Column('facture_ligne_id', sa.Integer(), nullable=True),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('fournisseur', sa.String(length=180), nullable=True),
    sa.Column('reference_piece', sa.String(length=120), nullable=True),
    sa.Column('mode_paiement', sa.String(length=50), nullable=True),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.Column('type_depense', sa.String(length=80), nullable=True),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('anomalie', sa.String(length=255), nullable=True),
    sa.Column('est_supprimee', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['charge_projet_id'], ['charge_projet.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facture_ligne_id'], ['facture_ligne.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ligne_budget_id'], ['ligne_budget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objectif_competence',
    sa.Column('objectif_id', sa.Integer(), nullable=False),
    sa.Column('competence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competence_id'], ['competence.id'], ),
    sa.ForeignKeyConstraint(['objectif_id'], ['objectif.id'], ),
    sa.PrimaryKeyConstraint('objectif_id', 'competence_id')
    )
    op.create_table('objectif_suivi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objectif_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('etat', sa.Integer(), nullable=False),
    sa.Column('ressenti', sa.Integer(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_saisie', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['objectif_id'], ['objectif.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session_activite.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objectif_suivi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objectif_suivi_date_saisie'), ['date_saisie'], unique=False)
        batch_op.create_index(batch_op.f('ix_objectif_suivi_objectif_id'), ['objectif_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_objectif_suivi_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_objectif_suivi_session_id'), ['session_id'], unique=False)

    op.create_table('question_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_group_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_group_id'], ['questionnaire_response_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depense_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depense_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['depense_id'], ['depense.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventaire_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secteur', sa.String(length=80), nullable=False),
    sa.Column('id_interne', sa.String(length=64), nullable=False),
    sa.Column('categorie', sa.String(length=120), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('marque', sa.String(length=120), nullable=True),
    sa.Column('modele', sa.String(length=120), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.String(length=180), nullable=True),
    sa.Column('etat', sa.String(length=50), nullable=False),
    sa.Column('localisation', sa.String(length=255), nullable=True),
    sa.Column('valeur_unitaire', sa.Float(), nullable=True),
    sa.Column('date_entree', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('facture_ligne_id', sa.Integer(), nullable=True),
    sa.Column('depense_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['depense_id'], ['depense.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facture_ligne_id'], ['facture_ligne.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_interne')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventaire_item')
    op.drop_table('depense_document')
    op.drop_table('question_response')
    with op.batch_alter_table('objectif_suivi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objectif_suivi_session_id'))
        batch_op.drop_index(batch_op.f('ix_objectif_suivi_participant_id'))
        batch_op.drop_index(batch_op.f('ix_objectif_suivi_objectif_id'))
        batch_op.drop_index(batch_op.f('ix_objectif_suivi_date_saisie'))

    op.drop_table('objectif_suivi')
    op.drop_table('objectif_competence')
    op.drop_table('depense')
    op.drop_table('ventilation_projet')
    op.drop_table('session_competence')
    op.drop_table('questionnaire_response_group')
    op.drop_table('projet_competence')
    op.drop_table('presence_activite')
    op.drop_table('objectif')
    op.drop_table('facture_ligne')
    op.drop_table('evaluation')
    op.drop_table('atelier_competence')
    with op.batch_alter_table('archive_emargement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archive_emargement_secteur'))

    op.drop_table('archive_emargement')
    op.drop_table('user_roles')
    op.drop_table('subvention_projet')
    with op.batch_alter_table('session_activite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_activite_secteur'))
        batch_op.drop_index(batch_op.f('ix_session_activite_rdv_date'))
        batch_op.drop_index(batch_op.f('ix_session_activite_kiosk_token'))
        batch_op.drop_index(batch_op.f('ix_session_activite_kiosk_pin'))
        batch_op.drop_index(batch_op.f('ix_session_activite_kiosk_open'))
        batch_op.drop_index(batch_op.f('ix_session_activite_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_session_activite_date_session'))

    op.drop_table('session_activite')
    op.drop_table('role_permissions')
    op.drop_table('questionnaire_secteur')
    op.drop_table('questionnaire_atelier')
    op.drop_table('question')
    with op.batch_alter_table('projet_indicateur', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projet_indicateur_projet_id'))

    op.drop_table('projet_indicateur')
    with op.batch_alter_table('projet_atelier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projet_atelier_projet_id'))
        batch_op.drop_index(batch_op.f('ix_projet_atelier_atelier_id'))

    op.drop_table('projet_atelier')
    op.drop_table('produit_projet')
    with op.batch_alter_table('periode_financement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_periode_financement_secteur'))
        batch_op.drop_index(batch_op.f('ix_periode_financement_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_periode_financement_date_fin'))
        batch_op.drop_index(batch_op.f('ix_periode_financement_date_debut'))

    op.drop_table('periode_financement')
    op.drop_table('participant')
    op.drop_table('partenaire_secteur')
    op.drop_table('partenaire_intervention')
    op.drop_table('ligne_budget')
    op.drop_table('facture_achat')
    op.drop_table('competence')
    op.drop_table('charge_projet')
    with op.batch_alter_table('bilan_lourd_narratif', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bilan_lourd_narratif_secteur'))
        batch_op.drop_index(batch_op.f('ix_bilan_lourd_narratif_annee'))

    op.drop_table('bilan_lourd_narratif')
    op.drop_table('atelier_capacite_mois')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('subvention')
    with op.batch_alter_table('secteur', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secteur_label'))
        batch_op.drop_index(batch_op.f('ix_secteur_code'))

    op.drop_table('secteur')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_code'))

    op.drop_table('role')
    op.drop_table('referentiel')
    op.drop_table('questionnaire')
    op.drop_table('quartier')
    op.drop_table('projet')
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_code'))
        batch_op.drop_index(batch_op.f('ix_permission_category'))

    op.drop_table('permission')
    op.drop_table('partenaire')
    op.drop_table('instance_settings')
    with op.batch_alter_table('atelier_activite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atelier_activite_secteur'))
        batch_op.drop_index(batch_op.f('ix_atelier_activite_is_deleted'))

    op.drop_table('atelier_activite')
    # ### end Alembic commands ###
